spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.generate_statistics=false
spring.thymeleaf.cache=true
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:true}

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

logging.level.com.flashcardapp=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
